### ISSUE TITLE
[BUG] SET_KINEMATIC_POSITION will sometimes cause "MCU 'tools' shutdown: Rescheduled timer in the past"

### ISSUE THREAD

**Issue by naikymen** [naikymen/klipper-for-cnc#6]

**Comment by naikymen** [comment]
After running this GCODE: [XYZABC.gcode.txt](https://github.com/naikymen/klipper-homing-extruder/files/10882215/XYZABC.gcode.txt)

An error popped up: `Internal error on command:"G28"`

Log: [klippy.log](https://github.com/naikymen/klipper-homing-extruder/files/10882201/klippy.log)

**Comment by naikymen** [comment]
Error message comes from stepcompress:

```
b'stepcompress o=0 i=0 c=46 a=0: Invalid sequence'
b'stepcompress o=0 i=0 c=46 a=0: Invalid sequence'
Internal error on command:"G28"Internal error in stepcompress
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/gcode.py", line 201, in _process_commands
    handler(gcmd)
  File "/home/pi/klipper/klippy/extras/homing.py", line 612, in cmd_G28
    self.home_axes(kin=kin_abc, homing_axes=[a for a in axes if a in [3,4,5]])
  File "/home/pi/klipper/klippy/extras/homing.py", line 636, in home_axes
    kin.home(homing_state)
  File "/home/pi/klipper/klippy/kinematics/cartesian_abc.py", line 145, in home
    self._home_axis(homing_state, axis, self.rails[toolhead.axes_to_xyz(axis)])
  File "/home/pi/klipper/klippy/kinematics/cartesian_abc.py", line 138, in _home_axis
    homing_state.home_rails([rail], forcepos, homepos)
  File "/home/pi/klipper/klippy/extras/homing.py", line 471, in home_rails
    hmove.homing_move(homepos, hi.speed)
  File "/home/pi/klipper/klippy/extras/homing.py", line 251, in homing_move
    drip_completion=all_endstop_trigger)
  File "/home/pi/klipper/klippy/toolhead.py", line 1013, in drip_move
    self.move_queue.flush()
  File "/home/pi/klipper/klippy/toolhead.py", line 272, in flush
    self.toolhead._process_moves(moves=queue[:flush_count])
  File "/home/pi/klipper/klippy/toolhead.py", line 652, in _process_moves
    self._update_drip_move_time(next_move_time)
  File "/home/pi/klipper/klippy/toolhead.py", line 979, in _update_drip_move_time
    self._update_move_time(next_print_time=npt)
  File "/home/pi/klipper/klippy/toolhead.py", line 485, in _update_move_time
    sg(sg_flush_time)
  File "/home/pi/klipper/klippy/stepper.py", line 259, in generate_steps
    raise error("Internal error in stepcompress")
stepper.error: Internal error in stepcompress
Transition to shutdown state: Internal error on command:"G28"
```

**Comment by naikymen** [comment]
I have seen `i=0 c=46` before.

**Comment by naikymen** [comment]
The G28 error was due to a regression in e89538858d0f08f90c7b276c858082fa3fa26775 and a9e2c3365260ced9d872f008cdb51a038f8ebc32

**Comment by naikymen** [comment]
Reverted SET_KINEMATIC_POSITION to XYZ only for now.

**Comment by naikymen** [comment]
I haven't observed this in a while. SET_KINEMATIC_POSITION is working well with ABC and E axes too.

I also just tested it a bit with simulavr. Closing as solved until it comes back. (?)
